# Generated by Django 2.2.2 on 2019-06-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'Todo'},
        ),
        migrations.AddField(
            model_name='todo',
            name='posted_by',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
